---
# Install PostgreSQL along with psycopg2-binary Python library that will
# allow us to use Ansible PostgreSQL modules.

- hosts: postgres

  pre_tasks:
    - name: "Install Postgres Packages"
      apt: "name={{ item }} state=present"
      with_items:
        - postgresql
        - postgresql-server

    - name: "Install Python packages"
      pip: "name={{ item }} state=present"
      with_items:
        - psycopg2-binary

  tasks:
    - name: "Find out if PostgreSQL is initialized"
      ansible.builtin.stat:
        path: "/var/lib/pgsql/data/pg_hba.conf"
      register: postgres_data

    - name: "Initialize PostgreSQL"
      shell: "postgresql-setup initdb"
      when: not postgres_data.stat.exists
    
    - name: "Start and enable services"
      service: "name={{ item }} state=started enabled=yes"
      with_items:
        - postgresql

  handlers:
    - name: restart postgres
      service: name=postgresql state=restarted
      
