---

- hosts: psql
  become: true
  vars:
    db_user: dbuser
    db_name: psql1
    db_password: password

  roles:
    - base               # base role refreshes repositories for Debian and CentOS
    - apt-inst-psql           # apt-inst installs PostgreSQL on Debian systems
    - dnf-inst-psql           # dnf-inst installs PostgreSQL on Debian systems
    - post-psql           # Post installation tasks to create and verify test DB

  tasks:
  
  - name: Populate service facts
    ansible.builtin.service_facts:

  