---
# Install PostgreSQL along with psycopg2-binary Python library that will
# allow us to use Ansible PostgreSQL modules.

- name: Talk to all host so we can learn about them
  hosts: all
  tasks:

    - name: classify hosts depending on distribution
      ansible.builtin.group_by:
        key: os_{{ ansible_facts['distribution'] }}

- hosts: os_Ubuntu
  gather_facts: False
  tasks:

    - name: Ping my Ubuntu hosts
      ansible.builtin.ping: