- hosts: localhost
  tags: setup
  connection: local
  become: true
  gather_facts: yes
  vars_files:
    - env.yaml

- hosts: postgresdb
  tags: postgres
  become: true
  gather_facts: yes
  roles:
    - postgresql
