vars:
  db_user: dbuser
  db_name: big-boy
  db_password: password
  mongoDB_Port: 27017

- name: Ensure the PostgreSQL service is running
  service:
    name: postgresql
    state: started
    enabled: yes

- name: Make sure test DB is not present
  become: true
  become_user: postgres
  postgresql_db:
    name={{ db_name }}
    state=absent

- name: "Find out if PostgreSQL is initialized"
  ansible.builtin.stat:
    path: "/var/lib/pgsql/data/pg_hba.conf"
  register: postgres_data

- name: "Initialize PostgreSQL"
  shell: "/usr/bin/postgresql-setup initdb"
  when: not postgres_data.stat.exists and ansible_distribution == "CentOS"

- name: Create DB specified in variables
  become: true
  become_user: postgres
  postgresql_db: 
    name={{ db_name }}
    template='template0'
    state=present

- name: Create DB user
  postgresql_user:
    state: present
    name: "{{ db_user }}"
    password: "{{ db_password }}"
  become: true
  become_user: postgres

- name: Ensure user has access to the new database
  become: true
  become_user: postgres
  postgresql_privs: 
    type: database 
    database: "{{ db_name }}"
    roles: "{{ db_user }}"
    grant_option: no
    privs: all

  
  