- name: Update repository index for Ubuntu
  apt:
    update_cache: yes
  when: ansible_distribution == "Ubuntu"
- name: Update repository index for CentOS
  dnf: 
    update_cache: yes
  when: ansible_distribution == "CentOS"